# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08\x62\x63.proto\"-\n\texcelData\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x12\n\nmeterusage\x18\x02 \x01(\t\"&\n\ntimeSeries\x12\x18\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\n.excelData\" \n\x0emetricResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\"!\n\rmetricRequest\x12\x10\n\x08sendFlag\x18\x01 \x01(\x05\x32:\n\x05usage\x12\x31\n\x0esendMetricData\x12\x0e.metricRequest\x1a\x0f.metricResponseb\x06proto3'
)




_EXCELDATA = _descriptor.Descriptor(
  name='excelData',
  full_name='excelData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='excelData.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meterusage', full_name='excelData.meterusage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=57,
)


_TIMESERIES = _descriptor.Descriptor(
  name='timeSeries',
  full_name='timeSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='timeSeries.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=97,
)


_METRICRESPONSE = _descriptor.Descriptor(
  name='metricResponse',
  full_name='metricResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='metricResponse.result', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=131,
)


_METRICREQUEST = _descriptor.Descriptor(
  name='metricRequest',
  full_name='metricRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sendFlag', full_name='metricRequest.sendFlag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=166,
)

_TIMESERIES.fields_by_name['data'].message_type = _EXCELDATA
DESCRIPTOR.message_types_by_name['excelData'] = _EXCELDATA
DESCRIPTOR.message_types_by_name['timeSeries'] = _TIMESERIES
DESCRIPTOR.message_types_by_name['metricResponse'] = _METRICRESPONSE
DESCRIPTOR.message_types_by_name['metricRequest'] = _METRICREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

excelData = _reflection.GeneratedProtocolMessageType('excelData', (_message.Message,), {
  'DESCRIPTOR' : _EXCELDATA,
  '__module__' : 'bc_pb2'
  # @@protoc_insertion_point(class_scope:excelData)
  })
_sym_db.RegisterMessage(excelData)

timeSeries = _reflection.GeneratedProtocolMessageType('timeSeries', (_message.Message,), {
  'DESCRIPTOR' : _TIMESERIES,
  '__module__' : 'bc_pb2'
  # @@protoc_insertion_point(class_scope:timeSeries)
  })
_sym_db.RegisterMessage(timeSeries)

metricResponse = _reflection.GeneratedProtocolMessageType('metricResponse', (_message.Message,), {
  'DESCRIPTOR' : _METRICRESPONSE,
  '__module__' : 'bc_pb2'
  # @@protoc_insertion_point(class_scope:metricResponse)
  })
_sym_db.RegisterMessage(metricResponse)

metricRequest = _reflection.GeneratedProtocolMessageType('metricRequest', (_message.Message,), {
  'DESCRIPTOR' : _METRICREQUEST,
  '__module__' : 'bc_pb2'
  # @@protoc_insertion_point(class_scope:metricRequest)
  })
_sym_db.RegisterMessage(metricRequest)



_USAGE = _descriptor.ServiceDescriptor(
  name='usage',
  full_name='usage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=168,
  serialized_end=226,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendMetricData',
    full_name='usage.sendMetricData',
    index=0,
    containing_service=None,
    input_type=_METRICREQUEST,
    output_type=_METRICRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USAGE)

DESCRIPTOR.services_by_name['usage'] = _USAGE

# @@protoc_insertion_point(module_scope)
